#!/usr/bin/env python3
"""Back-fill ``word-images/_library/`` from images that already exist in
per-set folders, so subsequent batch-generation runs correctly skip words
you've already generated.

Safe to run while ``tools/batch_generate_openai.py`` is generating images
in another terminal:
  * The script never overwrites an existing ``_library/`` file.
  * The script never deletes or moves anything.
  * If a word gets generated by the batch at the same moment, the batch's
    newer file lands in ``_library/`` and the backfill quietly skips it.

Usage (from the project root):

    python3 tools/backfill_library.py             # back-fill with safe defaults
    python3 tools/backfill_library.py --dry-run   # preview only, no files written
    python3 tools/backfill_library.py --no-suspicious-list  # skip writing the review file
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List, Set, Tuple


IMAGE_EXTENSIONS: Set[str] = {".png", ".jpg", ".jpeg", ".webp", ".gif"}


def find_repo_root(start: Path) -> Path:
    here = start.resolve()
    for candidate in [here, *here.parents]:
        if (candidate / "word-lists").is_dir() and (candidate / "word-images").is_dir():
            return candidate
    return start.resolve()


REPO_ROOT = find_repo_root(Path(__file__).parent)


def load_known_words(word_sets_path: Path) -> Set[str]:
    """Return a set of every word that appears in word-sets.json, lowercased."""
    if not word_sets_path.is_file():
        raise SystemExit(f"word-sets.json not found at: {word_sets_path}")
    with word_sets_path.open(encoding="utf-8") as handle:
        sets = json.load(handle)
    if not isinstance(sets, list):
        raise SystemExit("word-sets.json must be a JSON array of set objects.")
    known: Set[str] = set()
    for s in sets:
        for pair in s.get("pairs", []) or []:
            for raw in pair:
                if not raw:
                    continue
                word = str(raw).strip().lower()
                if word:
                    known.add(word)
    return known


def collect_set_folder_images(word_images_root: Path, library_dir: Path
                              ) -> Dict[str, List[Path]]:
    """Walk every folder under ``word-images/`` (except ``_library/``) and
    group images by their lowercase filename stem.
    """
    by_stem: Dict[str, List[Path]] = defaultdict(list)
    library_resolved = library_dir.resolve()
    for folder in sorted(word_images_root.iterdir()):
        if not folder.is_dir():
            continue
        if folder.resolve() == library_resolved:
            continue
        for path in folder.iterdir():
            if not path.is_file():
                continue
            if path.suffix.lower() not in IMAGE_EXTENSIONS:
                continue
            stem_lc = path.stem.strip().lower()
            if not stem_lc:
                continue
            by_stem[stem_lc].append(path)
    return by_stem


def index_library(library_dir: Path) -> Set[str]:
    if not library_dir.is_dir():
        return set()
    return {p.stem.strip().lower() for p in library_dir.iterdir()
            if p.is_file() and p.suffix.lower() in IMAGE_EXTENSIONS}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--word-sets", type=Path,
                        default=REPO_ROOT / "word-lists" / "word-sets.json")
    parser.add_argument("--word-images-root", type=Path,
                        default=REPO_ROOT / "word-images")
    parser.add_argument("--library-dir", type=Path,
                        default=REPO_ROOT / "word-images" / "_library")
    parser.add_argument("--suspicious-file", type=Path,
                        default=REPO_ROOT / "tools" / "library-backfill-suspicious.txt",
                        help="Where to write the list of skipped 'suspicious' "
                             "filenames whose stems don't match any word in "
                             "word-sets.json.")
    parser.add_argument("--no-suspicious-list", dest="write_suspicious",
                        action="store_false", default=True,
                        help="Don't write the suspicious-filenames review file.")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would happen; don't copy any files.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()

    known_words = load_known_words(args.word_sets)
    by_stem = collect_set_folder_images(args.word_images_root, args.library_dir)
    library_stems = index_library(args.library_dir)

    args.library_dir.mkdir(parents=True, exist_ok=True)

    copied: List[Tuple[Path, Path]] = []
    skipped_existing: List[str] = []
    skipped_suspicious: Dict[str, List[Path]] = {}
    conflicts: List[Tuple[str, Path, int, int]] = []  # (stem, winner, winner_size, n_candidates)

    for stem_lc, paths in sorted(by_stem.items()):
        # Already in library? Never overwrite.
        if stem_lc in library_stems:
            skipped_existing.append(stem_lc)
            continue

        # Filename whose stem isn't in word-sets.json -> flag for review.
        if stem_lc not in known_words:
            skipped_suspicious[stem_lc] = paths
            continue

        # Pick the largest-by-bytes copy; tie-break by newest mtime.
        def sort_key(p: Path) -> Tuple[int, float]:
            try:
                st = p.stat()
                return (st.st_size, st.st_mtime)
            except OSError:
                return (0, 0.0)

        winner = max(paths, key=sort_key)
        dest = args.library_dir / winner.name

        if dest.exists():
            # Race: library now has a copy (batch wrote it). Skip safely.
            skipped_existing.append(stem_lc)
            continue

        if len(paths) > 1:
            try:
                conflicts.append((stem_lc, winner, winner.stat().st_size, len(paths)))
            except OSError:
                conflicts.append((stem_lc, winner, 0, len(paths)))

        if args.dry_run:
            copied.append((winner, dest))
        else:
            try:
                shutil.copy2(winner, dest)
                copied.append((winner, dest))
            except Exception as exc:  # noqa: BLE001
                print(f"  [fail] {winner} -> {dest}: {type(exc).__name__}: {exc}")

    # Write the suspicious list if requested.
    if args.write_suspicious and skipped_suspicious:
        if not args.dry_run:
            args.suspicious_file.parent.mkdir(parents=True, exist_ok=True)
            with args.suspicious_file.open("w", encoding="utf-8") as fh:
                fh.write("# Files in set folders whose stems don't match any word\n"
                         "# in word-lists/word-sets.json. Review and either:\n"
                         "#   - rename the file in its folder to match a real word, OR\n"
                         "#   - delete it if it's junk, OR\n"
                         "#   - add the word to your Google Sheet / word-sets.json.\n"
                         "#\n")
                for stem, paths in sorted(skipped_suspicious.items()):
                    fh.write(f"\n[{stem}]\n")
                    for p in paths:
                        try:
                            rel = p.relative_to(REPO_ROOT)
                        except ValueError:
                            rel = p
                        fh.write(f"  {rel}\n")

    # Print a summary.
    label = "Would copy" if args.dry_run else "Copied"
    print(f"Library backfill summary:")
    print(f"  Word images root: {args.word_images_root}")
    print(f"  Library dir:      {args.library_dir}")
    print(f"  word-sets.json:   {args.word_sets}")
    print()
    print(f"  Unique stems found in set folders: {len(by_stem)}")
    print(f"  Stems already in _library/:        {len(skipped_existing)}")
    print(f"  Stems with no matching word in word-sets.json (skipped): "
          f"{len(skipped_suspicious)}")
    print(f"  {label} into _library/: {len(copied)}")
    if conflicts:
        print(f"  Stems that existed in 2+ folders (largest wins): {len(conflicts)}")
    if args.write_suspicious and skipped_suspicious and not args.dry_run:
        print(f"  Suspicious filenames written to: {args.suspicious_file}")
    elif args.dry_run and skipped_suspicious:
        print(f"  (Would also write {len(skipped_suspicious)} suspicious entries "
              f"to: {args.suspicious_file})")

    if copied:
        sample = copied[:10]
        print(f"\nFirst {len(sample)} {'planned copies' if args.dry_run else 'copies'}:")
        for src, dest in sample:
            try:
                rel_src = src.relative_to(REPO_ROOT)
            except ValueError:
                rel_src = src
            print(f"  {rel_src}  ->  _library/{dest.name}")
        if len(copied) > len(sample):
            print(f"  ... plus {len(copied) - len(sample)} more.")

    if skipped_suspicious:
        sample = list(skipped_suspicious.items())[:10]
        print(f"\nFirst {len(sample)} suspicious filenames (skipped):")
        for stem, paths in sample:
            try:
                rel = paths[0].relative_to(REPO_ROOT)
            except ValueError:
                rel = paths[0]
            extra = f"  (+{len(paths) - 1} more copies)" if len(paths) > 1 else ""
            print(f"  {rel}{extra}")
        if len(skipped_suspicious) > len(sample):
            print(f"  ... plus {len(skipped_suspicious) - len(sample)} more.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
